name: Polymorph
favicon: null
layout_spectrum: 0.21981
typography_spectrum: 0.3851363454014063
title: The ghost of a website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d2538'
    - '#cfcbc0'
    - '#eee9d6'
    - '#7a90a5'
    - '#c49979'
  brandStrength: 0.6875
  lightness: 0.14830423262901604
  saturation: 0.8125
  rhythmicContrast: 0.6654250842984766
purpose: []
