name: Polymorph
favicon: null
layout_spectrum: 0.4630456273443997
typography_spectrum: 0.3851363454014063
title: The ghost of a website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8355387900955975
  lightness: 0.14830423262901604
  saturation: 0.9826045411173254
  rhythmicContrast: 0.6654250842984766
purpose: []
