name: Polymorph
favicon: null
layout_spectrum: 0.21981
typography_spectrum: 0.92973
title: The ghost of a website
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2d2926'
    - '#050505'
    - '#5d5a55'
    - '#b4ae9e'
    - '#d8d2c2'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
